// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace ProductManagement.Dal.Entity
{
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string FullDescription { get; set; }
        public string ShortDescription { get; set; }
        public decimal Price { get; set; }
        public bool Published { get; set; }

    }
}